app1/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    re_path('^$', views.homepage, name="homepage"),
    re_path('^add-task', views.add_task, name="add_task"),
    path('<int:pk>/share-task', views.share_task, name='share_task'),
    path('<int:pk>/edit-task', views.edit_task, name='edit_task'),
    path('<int:pk>/view-task', views.view_task, name='view_task'),
]

new_todo_app/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('app1.urls')),
    re_path(r'^accounts/', include('accounts.urls')),
]

app1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Task(models.Model):
    goal = models.CharField(max_length=150, verbose_name="Goal")
    description = models.TextField(verbose_name="Task description")
    created_date = models.DateTimeField()
    end_date = models.DateTimeField()
    by_who = models.CharField(max_length=150, verbose_name="Created by")
    viewable_by = models.ManyToManyField(User, related_name="viewable_by")
    editable_by = models.ManyToManyField(User, related_name="editable_by")

    class Meta:
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'

    def __str__(self):
        return self.goal


class Comment(models.Model):
    comment_sender = models.CharField(verbose_name="Comment author", max_length=250)
    comment_text = models.CharField(verbose_name="Comment text", max_length=250)
    comment_date = models.DateTimeField(default=timezone.now)
    comment_related_task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment_sender + ' - ' + self.comment_text

app1/forms.py
from django import forms
from .models import Task, Comment


class DateTimeInput(forms.DateTimeInput):
    input_type = "date"


class AddNewTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['goal', 'description', 'end_date']
        widgets = {'end_date': DateTimeInput()}


class ShareTask(forms.Form):
    share_with = forms.CharField(max_length=250, widget=forms.TimeInput(attrs={'placeholder': 'Enter a username'}))
    editable = forms.BooleanField(required=False)


class LeaveComment(forms.ModelForm):
    comment_text = forms.CharField(label='', max_length=250,
                                   widget=forms.Textarea(attrs={'placeholder': 'Comment text',
                                                                'style': 'resize:none; height:100px;'
                                                                }))

    class Meta:
        model = Comment
        fields = ['comment_text']

app1/views.py
from django.shortcuts import render
from .models import Task, Comment
#from .tasks import test_task
from .forms import AddNewTaskForm, ShareTask
from django.utils import timezone
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import LeaveComment


def homepage(request):
    todo_tasks = Task.objects.filter(by_who__exact=request.user)
    shared_todo_tasks = Task.objects.filter(viewable_by__username__exact=request.user)
    shared_todo_tasks_to_edit = Task.objects.filter(editable_by__username__exact=request.user)
    return render(request, 'app1/homepage.html', {'todo_tasks': todo_tasks,
                                                  'shared_todo_tasks': shared_todo_tasks,
                                                  'shared_todo_tasks_to_edit': shared_todo_tasks_to_edit})


@login_required(login_url="login")
def add_task(request):
    if request.method == "POST":
        form = AddNewTaskForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.by_who = request.user
            form.created_date = timezone.now()
            form.save()
            return redirect('homepage')
        else:
            form = AddNewTaskForm()
            return render(request, 'app1/add-task.html', {'form': form})
    else:
        form = AddNewTaskForm()
        return render(request, 'app1/add-task.html',  {'form': form})


@login_required(login_url="login")
def share_task(request, pk=None):
    """Share the task by its ID with other user by username"""
    if request.method == "POST":
        form = ShareTask(request.POST)
        if form.is_valid():
            username_to_share = form.cleaned_data['share_with']
            if User.objects.filter(username__exact=username_to_share):
                task = Task.objects.get(pk=pk)
                if form.cleaned_data['editable'] is True:
                    task.viewable_by.add(User.objects.get(username__exact=username_to_share))
                    task.editable_by.add(User.objects.get(username__exact=username_to_share))
                    return redirect('homepage')
                else:
                    task.viewable_by.add(User.objects.get(username__exact=username_to_share))
                    return redirect('homepage')
            else:
                form = ShareTask()
                return render(request, 'app1/share-task.html', {'form': form, 'error': "User doesnt exist"})
        return render(request, 'app1/share-task.html', {'form': form})
    else:
        form = ShareTask()
        return render(request, 'app1/share-task.html', {'form': form})


@login_required(login_url="login")
def edit_task(request, pk=None):
    """Edit task with id of pk"""
    task = get_object_or_404(Task, pk=pk)
    if str(request.user) == task.by_who:
        if request.method == "POST":
            form = AddNewTaskForm(request.POST, instance=task)
            if form.is_valid():
                form = form.save(commit=False)
                form.by_who = str(request.user)
                form.created_date = timezone.now()
                form.save()
                return redirect('homepage')
            else:
                form = AddNewTaskForm(instance=task)
                return render(request, 'app1/edit-task.html', {'form': form})
        else:
            form = AddNewTaskForm(instance=task)
            return render(request, 'app1/edit-task.html', {'form': form})
    else:
        return redirect('homepage')


@login_required(login_url='login')
def view_task(request, pk=None):
    """View task as a card, detailed form with comment section"""
    if request.method == "POST":
        form = LeaveComment(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.comment_sender = str(request.user)
            form.comment_date = timezone.now()
            form.comment_related_task = Task.objects.get(pk=pk)
            form.save()
            return redirect('view_task', pk=pk)
        else:
            form = LeaveComment()
            return render(request, 'app1/view-task.html', {'form': form})
    else:
        task = Task.objects.get(pk=pk)
        comments = Comment.objects.filter(comment_related_task_id=pk)
        form = LeaveComment()
        context = {
            'task': task,
            'comments': comments,
            'leave_comment_form': form
        }
    return render(request, 'app1/view-task.html', context)

templates/app1/add-task.html
{% extends 'main/main.html' %}


{% block content %}
    <div class="container mt-5">
        <div class="col-md-4 offset-4">
            <form method="post">
                {% csrf_token %}
                {{ form.as_ul }}
                <button type="submit" class="btn btn-success">Add task</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/app1/edit-task.html
{% extends 'main/main.html' %}

<title>Edit task</title>

{% block content %}
    <div class="container mt-5">
        <div class="col-md-4 offset-4">
            <form method="post">
                {% csrf_token %}
                {{ form.as_ul }}
                <button type="submit" class="btn btn-success">Save changes</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/app1/homepage.html
{% extends 'main/main.html' %}

{% block title %}
    <title>Home</title>
{% endblock title %}

{% block content %}


    <div class="container mt-5">
        <div class="row">


            {% for task in todo_tasks %}
                <div class="col-md-4 mt-3">
                    <div class="list-group">
                        <div class="list-group-item">
                            <div class="d-flex w-100 justify-content-between">
                                <a href="{{ task.id }}/view-task"><h5 class="mb-1">{{ task.goal }}</h5></a>
                                <small>{{ task.created_date }}</small>
                            </div>

                            <p class="mb-1">{{ task.description|truncatechars:25}}</p>
                            <p><small>Deadline: {{ task.end_date|date }}</small></p>
                            <a href="{{ task.id }}/share-task" class="btn btn-warning" style="width: 100%;">Share
                                with
                            </a>
                            <a href="{{ task.id }}/edit-task" class="btn btn-success" style="width: 100%;">Edit
                                task
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}

            {% for shared_task in shared_todo_tasks %}
                <div class="col-md-4 mt-3">
                    <div class="list-group">
                        <div class="list-group-item">
                            <div class="d-flex w-100 justify-content-between">
                                <a href="#"><h5 class="mb-1">{{ shared_task.goal }}</h5></a>
                                <small>{{ shared_task.created_date }}</small>
                            </div>
                            <p class="mb-1">{{ shared_task.description|truncatechars:25 }}</p>
                            <small>Deadline: {{ shared_task.end_date|date }}</small><br>
                            <small><b>By: {{ shared_task.by_who }}</b></small>

                            <a href="#" class="btn btn-warning disabled" style="width: 100%;">Share
                                with
                            </a>

                            {% if shared_task in shared_todo_tasks_to_edit %}
                                <a href="{{ shared_task.id }}/view-task" class="btn btn-success" style="width: 100%;">View detailed</a>
                            {% else %}
                                <a href="#" class="btn btn-success disabled" style="width: 100%;">Edit
                                    task
                                </a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            {% endfor %}


        </div>
    </div>

{% endblock content %}

templates/app1/share-task.html
{% extends 'main/main.html' %}

{% block title %}
    <title>Share task</title>
{% endblock title %}



{% block content %}
    <div class="container mt-5">
        <div class="col-md-4 offset-4">
            {% if error %}
                <p class="alert-danger">{{ error }}</p>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_ul }}
                <button type="submit">Share</button>
            </form>

        </div>
    </div>
{% endblock content %}

templates/app1/view-task.html
{% extends 'main/main.html' %}



{% block title %}
    <title>Task details</title>
{% endblock title %}



{% block content %}

    <div class="container">
        <div class="row">

            <!-- Task -->
            <div class="col-md-6 offset-1">
                <div class="card text-center">
                    <div class="card-header">
                        Task by: <b>{{ task.by_who }}</b>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><b>Task:</b> {{ task.goal }}</h5>
                        <p class="card-text">{{ task.description }}</p>
                    </div>
                    <div class="card-footer text-muted">
                        <p>Created: <b>{{ task.created_date }}</b></p>
                        <p>Expires on: <b>{{ task.end_date }}</b></p>
                    </div>
                </div>
            </div>


            <!-- Comments -->
            <div class="col-md-5">
                <h2 class="text-center">Comments:</h2>

                <!-- Initial comment -->
                <form method="post">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-header" style="background-color: #e1ecf4">
                            Comment by: {{ request.user.get_username }}
                        </div>
                        <div class="card-body">
                            {{ leave_comment_form }}
                            <button id="submit-comment" type="submit" class="btn btn-success" style="align-items: center">Comment</button>
                        </div>
                        <div class="card-footer text-muted">
                            Now
                        </div>
                    </div>
                </form>

            <div id="comments" class="mt-3">
                <!-- Parse comments from db -->
                {% for comment in comments %}
                    <div class="card">
                        <div class="card-header" style="background-color: #e1ecf4">
                            Comment by: {{ comment.comment_sender }}
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ comment.comment_text }}</p>
                        </div>
                        <div class="card-footer text-muted">
                            {{ comment.comment_date }}
                        </div>
                    </div>
                    <br>
                {% endfor %}
            </div>

            </div>
        </div>
    </div>


<script>

    var task_id = "{{ task.id|escapejs }}";

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/' + task_id + '/view-task');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        var sender = "{{ request.user }}";
        console.log("Message received from backend: " + message + '\n');
        var today = new Date();
        var date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();
        var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
        var dateTime = today.getDate() + ' ' + date + ' '+ time;
        createComment(sender, message, dateTime, data['date_created']);
    };

    chatSocket.onclose = function(event) {
      if (event.wasClean) {
        console.log(`[close] Connection closed cleanly, code=${event.code} reason=${event.reason}`);
      } else {
        // e.g. server process killed or network down
        // event.code is usually 1006 in this case
        console.log('[close] Connection died');
      }
    };

    chatSocket.onopen = function(e) {
        console.log('Connected!');
    };

    chatSocket.onerror = function(error) {
        console.log(`[error] ${error.message}`);
    };

    // sends message to backend
    document.querySelector('#submit-comment').onclick = function(e) {
        var messageInputDom = document.querySelector('#id_comment_text');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'sender' : "{{ request.user }}",
            'related_task_id': task_id
        }));

        messageInputDom.value = '';
    };


     function createComment(comment_sender, comment_text, comment_date) {
        var card = document.createElement('div');
        card.className = "card";

        var card_header = document.createElement('div');
        card_header.className = 'card-header';
        card_header.innerText = 'Comment by: ' + comment_sender;
        card.appendChild(card_header);

        var card_body = document.createElement('div');
        card_body.className = 'card-body';

        var card_text = document.createElement('p');
        card_text.className = 'card-text';
        card_text.innerText = comment_text;
        card_body.appendChild(card_text);
        card.appendChild(card_body);

        var card_footer = document.createElement('div');
        card_footer.className = 'card-footer text-muted';
        card_footer.innerText = "Now";
        card.appendChild(card_footer);
        document.getElementById('comments').appendChild(card);
    }
</script>

{% endblock content %}